filebeat.inputs:
- type: log
  paths:
    - /var/log/*.log
output.logstash:
  hosts: ["192.168.1.104:5044"]
 # ssl.certificate_authorities: ["/Users/Guangjie.Feng/localdisk/elastic/certificates/ca.crt"]
 # ssl.certificate: "/Users/Guangjie.Feng/localdisk/elastic/certificates/client.crt"
 # ssl.key: "/Users/Guangjie.Feng/localdisk/elastic/certificates/client.key"
filebeat.config.modules.path: 
  ${path.config}/modules.d/*.yml 
